### ISSUE TITLE
Room name should be checked for uniqueness

### ISSUE THREAD

**Issue by JamesClough** [sarrionandia/tournatrack#31]
You can add a room when there is already an existing room with the same name. This could lead to confusion.

**Comment by sarrionandia** [comment]
This issue isn't critical, but is a minor annoyance. 

Enforcing uniqueness at the database level is a pain for AppEngine. I'm going to add a Javascript check into the Room page instead.

**Comment by sarrionandia** [comment]
Fix commited, will be rolled out in milestone 4.
