### ISSUE TITLE
Tournatrack Homescreen

### ISSUE THREAD

**Issue by nzervoudis** [sarrionandia/tournatrack#38]
Homescreen should not just include your own competitions (i.e. the ones you've created), but also the ones you've regged for. There should also be a separate listing of all available competitions, potentially with the option to restrict based on geography, format, or other factors (e.g. NAMDA, IONA, Pro-Am, IV, Novice, BP, Australs, Schools, Composites Accepted, Judge Funding Available, Size 60-100 teams, Reg £15-35).

**Comment by sarrionandia** [comment]
Implemented: A list of tournaments is on the home screen. Australs etc. are not going to be supported.

Capability to browse for IVs will be considered later.
